package com.antshorttv.common;

public enum ErrorCode {
    UNAUTHORIZED,
    FORBIDDEN,
    VALIDATION_ERROR,
    DUPLICATE_MOBILE,
    INVALID_CREDENTIALS,
    TENANT_DISABLED,
    MEMBER_REMOVED,
    OWNER_LEAVE_BLOCKED,
    INVITATION_EXPIRED,
    DUPLICATE_PENDING_INVITATION,
    ALREADY_TENANT_MEMBER,
    NOT_FOUND
}
