package com.antshorttv.ai;

import com.antshorttv.authsession.AuthenticatedUser;
import com.antshorttv.common.BusinessException;
import com.antshorttv.common.ErrorCode;
import com.antshorttv.operationlog.OperationLogService;
import com.antshorttv.operationlog.OperationResult;
import com.antshorttv.security.CurrentPrincipal;
import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import jakarta.servlet.http.HttpServletRequest;
import java.time.LocalDateTime;
import java.util.List;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

record EditableAgentRequest(String name, String description, String promptTemplate, String outputSchema) {}
record EditableSkillRequest(String name, String category, String content) {}
record EditableAgentResponse(String code, Integer versionNo, String name, String description, String promptTemplate, String outputSchema, String status, Boolean published) {}
record EditableSkillResponse(String code, Integer versionNo, String name, String category, String content, String status, Boolean published) {}

@Service
public class EditableAiDefinitionService {
    private final AiAgentDefinitionMapper agentMapper; private final AiSkillDefinitionMapper skillMapper;
    private final CurrentPrincipal principal; private final OperationLogService operationLog; private final JdbcTemplate jdbc;
    public EditableAiDefinitionService(AiAgentDefinitionMapper a, AiSkillDefinitionMapper s, CurrentPrincipal p, OperationLogService o, JdbcTemplate j) { agentMapper=a; skillMapper=s; principal=p; operationLog=o; jdbc=j; }
    public List<EditableAgentResponse> agents() { principal.require(); return agentMapper.selectList(new LambdaQueryWrapper<AiAgentDefinitionEntity>().orderByAsc(AiAgentDefinitionEntity::getCode).orderByDesc(AiAgentDefinitionEntity::getVersionNo)).stream().map(this::agentResponse).toList(); }
    public List<EditableSkillResponse> skills() { principal.require(); return skillMapper.selectList(new LambdaQueryWrapper<AiSkillDefinitionEntity>().orderByAsc(AiSkillDefinitionEntity::getCode).orderByDesc(AiSkillDefinitionEntity::getVersionNo)).stream().map(this::skillResponse).toList(); }
    public String previewAgent(String code, java.util.Map<String, Object> variables) { principal.require(); AiAgentDefinitionEntity e=latestAgent(code); String prompt=e.getPromptTemplate(); if(variables!=null) for(var entry:variables.entrySet()) prompt=prompt.replace("${"+entry.getKey()+"}",String.valueOf(entry.getValue())); return prompt; }
    @Transactional public EditableAgentResponse updateAgent(String code, EditableAgentRequest r, HttpServletRequest req) { AuthenticatedUser u=principal.require(); if(r==null||blank(r.name())||blank(r.promptTemplate())) throw new BusinessException(ErrorCode.VALIDATION_ERROR,"Agent 名称和提示词不能为空。"); AiAgentDefinitionEntity published=publishedAgent(code); int v=nextAgentVersion(code); AiAgentDefinitionEntity e=new AiAgentDefinitionEntity(); e.setCode(code); e.setVersionNo(v); e.setName(r.name().trim()); e.setDescription(r.description()); e.setPromptTemplate(r.promptTemplate()); e.setOutputSchema(r.outputSchema()); e.setStatus("ENABLED"); e.setPublished(false); e.setCreatedBy(u.userId()); e.setCreatedAt(LocalDateTime.now()); e.setUpdatedAt(LocalDateTime.now()); agentMapper.insert(e); if(published!=null&&e.getId()!=null){jdbc.update("insert into ai_agent_skill (agent_definition_id, skill_definition_id) select ?, skill_definition_id from ai_agent_skill where agent_definition_id = ?",e.getId(),published.getId());} operationLog.record(u.userId(),null,"UPDATE_AI_AGENT_DEFINITION",e.getId(),OperationResult.SUCCESS,req); return agentResponse(e); }
    @Transactional public EditableSkillResponse updateSkill(String code, EditableSkillRequest r, HttpServletRequest req) { AuthenticatedUser u=principal.require(); if(r==null||blank(r.name())||blank(r.content())) throw new BusinessException(ErrorCode.VALIDATION_ERROR,"Skill 名称和内容不能为空。"); int v=nextSkillVersion(code); AiSkillDefinitionEntity e=new AiSkillDefinitionEntity(); e.setCode(code); e.setVersionNo(v); e.setName(r.name().trim()); e.setCategory(r.category()); e.setContent(r.content()); e.setStatus("ENABLED"); e.setPublished(false); e.setCreatedBy(u.userId()); e.setCreatedAt(LocalDateTime.now()); e.setUpdatedAt(LocalDateTime.now()); skillMapper.insert(e); operationLog.record(u.userId(),null,"UPDATE_AI_SKILL_DEFINITION",e.getId(),OperationResult.SUCCESS,req); return skillResponse(e); }
    @Transactional public EditableAgentResponse publishAgent(String code,HttpServletRequest req){ AuthenticatedUser u=principal.require(); AiAgentDefinitionEntity e=agentMapper.selectOne(new LambdaQueryWrapper<AiAgentDefinitionEntity>().eq(AiAgentDefinitionEntity::getCode,code).orderByDesc(AiAgentDefinitionEntity::getVersionNo).last("limit 1")); if(e==null) throw new BusinessException(ErrorCode.AI_MODEL_NOT_FOUND,"Agent 不存在。"); clearAgentPublished(code); e.setPublished(true); agentMapper.updateById(e); operationLog.record(u.userId(),null,"PUBLISH_AI_AGENT_DEFINITION",e.getId(),OperationResult.SUCCESS,req); return agentResponse(e); }
    @Transactional public EditableSkillResponse publishSkill(String code,HttpServletRequest req){ AuthenticatedUser u=principal.require(); AiSkillDefinitionEntity e=skillMapper.selectOne(new LambdaQueryWrapper<AiSkillDefinitionEntity>().eq(AiSkillDefinitionEntity::getCode,code).orderByDesc(AiSkillDefinitionEntity::getVersionNo).last("limit 1")); if(e==null) throw new BusinessException(ErrorCode.AI_MODEL_NOT_FOUND,"Skill 不存在。"); clearSkillPublished(code); e.setPublished(true); skillMapper.updateById(e); jdbc.update("insert into ai_agent_skill (agent_definition_id, skill_definition_id) select distinct x.agent_definition_id, ? from ai_agent_skill x join ai_skill_definition old on old.id = x.skill_definition_id where old.code = ? and not exists (select 1 from ai_agent_skill current_binding where current_binding.agent_definition_id = x.agent_definition_id and current_binding.skill_definition_id = ?)",e.getId(),code,e.getId()); operationLog.record(u.userId(),null,"PUBLISH_AI_SKILL_DEFINITION",e.getId(),OperationResult.SUCCESS,req); return skillResponse(e); }
    @Transactional public EditableAgentResponse setAgentStatus(String code,String status,HttpServletRequest req){ AuthenticatedUser u=principal.require(); AiAgentDefinitionEntity e=latestAgent(code); e.setStatus(normalizeStatus(status)); agentMapper.updateById(e); operationLog.record(u.userId(),null,"UPDATE_AI_AGENT_STATUS",e.getId(),OperationResult.SUCCESS,req); return agentResponse(e); }
    @Transactional public EditableSkillResponse setSkillStatus(String code,String status,HttpServletRequest req){ AuthenticatedUser u=principal.require(); AiSkillDefinitionEntity e=latestSkill(code); e.setStatus(normalizeStatus(status)); skillMapper.updateById(e); operationLog.record(u.userId(),null,"UPDATE_AI_SKILL_STATUS",e.getId(),OperationResult.SUCCESS,req); return skillResponse(e); }
    @Transactional public EditableAgentResponse rollbackAgent(String code,Integer version,HttpServletRequest req){ AuthenticatedUser u=principal.require(); AiAgentDefinitionEntity target=agentMapper.selectOne(new LambdaQueryWrapper<AiAgentDefinitionEntity>().eq(AiAgentDefinitionEntity::getCode,code).eq(AiAgentDefinitionEntity::getVersionNo,version)); if(target==null) throw new BusinessException(ErrorCode.VALIDATION_ERROR,"Agent 版本不存在。"); clearAgentPublished(code); target.setPublished(true); target.setStatus("ENABLED"); agentMapper.updateById(target); operationLog.record(u.userId(),null,"ROLLBACK_AI_AGENT_DEFINITION",target.getId(),OperationResult.SUCCESS,req); return agentResponse(target); }
    @Transactional public EditableSkillResponse rollbackSkill(String code,Integer version,HttpServletRequest req){ AuthenticatedUser u=principal.require(); AiSkillDefinitionEntity target=skillMapper.selectOne(new LambdaQueryWrapper<AiSkillDefinitionEntity>().eq(AiSkillDefinitionEntity::getCode,code).eq(AiSkillDefinitionEntity::getVersionNo,version)); if(target==null) throw new BusinessException(ErrorCode.VALIDATION_ERROR,"Skill 版本不存在。"); clearSkillPublished(code); target.setPublished(true); target.setStatus("ENABLED"); skillMapper.updateById(target); propagateSkillBindings(code,target.getId()); operationLog.record(u.userId(),null,"ROLLBACK_AI_SKILL_DEFINITION",target.getId(),OperationResult.SUCCESS,req); return skillResponse(target); }
    private int nextAgentVersion(String c){AiAgentDefinitionEntity e=agentMapper.selectOne(new LambdaQueryWrapper<AiAgentDefinitionEntity>().eq(AiAgentDefinitionEntity::getCode,c).orderByDesc(AiAgentDefinitionEntity::getVersionNo).last("limit 1"));return e==null?1:e.getVersionNo()+1;}
    private int nextSkillVersion(String c){AiSkillDefinitionEntity e=skillMapper.selectOne(new LambdaQueryWrapper<AiSkillDefinitionEntity>().eq(AiSkillDefinitionEntity::getCode,c).orderByDesc(AiSkillDefinitionEntity::getVersionNo).last("limit 1"));return e==null?1:e.getVersionNo()+1;}
    private AiAgentDefinitionEntity latestAgent(String c){AiAgentDefinitionEntity e=agentMapper.selectOne(new LambdaQueryWrapper<AiAgentDefinitionEntity>().eq(AiAgentDefinitionEntity::getCode,c).orderByDesc(AiAgentDefinitionEntity::getVersionNo).last("limit 1")); if(e==null) throw new BusinessException(ErrorCode.VALIDATION_ERROR,"Agent 不存在。"); return e;}
    private AiAgentDefinitionEntity publishedAgent(String c){return agentMapper.selectOne(new LambdaQueryWrapper<AiAgentDefinitionEntity>().eq(AiAgentDefinitionEntity::getCode,c).eq(AiAgentDefinitionEntity::getPublished,true).orderByDesc(AiAgentDefinitionEntity::getVersionNo).last("limit 1"));}
    private AiSkillDefinitionEntity latestSkill(String c){AiSkillDefinitionEntity e=skillMapper.selectOne(new LambdaQueryWrapper<AiSkillDefinitionEntity>().eq(AiSkillDefinitionEntity::getCode,c).orderByDesc(AiSkillDefinitionEntity::getVersionNo).last("limit 1")); if(e==null) throw new BusinessException(ErrorCode.VALIDATION_ERROR,"Skill 不存在。"); return e;}
    private String normalizeStatus(String status){ if("enable".equalsIgnoreCase(status)) return "ENABLED"; if("disable".equalsIgnoreCase(status)) return "DISABLED"; throw new BusinessException(ErrorCode.VALIDATION_ERROR,"状态只能是 enable 或 disable。"); }
    private void clearAgentPublished(String c){for(AiAgentDefinitionEntity e:agentMapper.selectList(new LambdaQueryWrapper<AiAgentDefinitionEntity>().eq(AiAgentDefinitionEntity::getCode,c).eq(AiAgentDefinitionEntity::getPublished,true))){e.setPublished(false);agentMapper.updateById(e);}}
    private void clearSkillPublished(String c){for(AiSkillDefinitionEntity e:skillMapper.selectList(new LambdaQueryWrapper<AiSkillDefinitionEntity>().eq(AiSkillDefinitionEntity::getCode,c).eq(AiSkillDefinitionEntity::getPublished,true))){e.setPublished(false);skillMapper.updateById(e);}}
    private void propagateSkillBindings(String code,Long skillId){jdbc.update("insert into ai_agent_skill (agent_definition_id, skill_definition_id) select distinct x.agent_definition_id, ? from ai_agent_skill x join ai_skill_definition old on old.id = x.skill_definition_id where old.code = ? and not exists (select 1 from ai_agent_skill current_binding where current_binding.agent_definition_id = x.agent_definition_id and current_binding.skill_definition_id = ?)",skillId,code,skillId);}
    private boolean blank(String s){return s==null||s.isBlank();}
    private EditableAgentResponse agentResponse(AiAgentDefinitionEntity e){return new EditableAgentResponse(e.getCode(),e.getVersionNo(),e.getName(),e.getDescription(),e.getPromptTemplate(),e.getOutputSchema(),e.getStatus(),e.getPublished());}
    private EditableSkillResponse skillResponse(AiSkillDefinitionEntity e){return new EditableSkillResponse(e.getCode(),e.getVersionNo(),e.getName(),e.getCategory(),e.getContent(),e.getStatus(),e.getPublished());}
}
