create table if not exists inspiration_creation (
  id bigint primary key auto_increment,
  external_id varchar(64) not null,
  external_task_id varchar(64) null,
  creation_type varchar(16) not null,
  task_type varchar(128) not null,
  title varchar(200) not null,
  author_name varchar(100) not null,
  url varchar(1000) not null,
  storage_path varchar(1000) not null,
  mime_type varchar(100) null,
  file_size bigint null,
  detail_json longtext null,
  source_created_at datetime null,
  source_updated_at datetime null,
  import_status varchar(32) not null,
  import_error text null,
  sort_order int not null default 0,
  created_at datetime not null,
  updated_at datetime not null,
  unique key uk_inspiration_creation_external_id (external_id),
  index idx_inspiration_creation_import_order (import_status, sort_order, id),
  index idx_inspiration_creation_external_task (external_task_id)
);

