create table review_project (
  id bigint primary key auto_increment,
  tenant_id bigint not null,
  name varchar(200) not null,
  source_file_name varchar(255) null,
  source_type varchar(32) not null,
  original_content longtext not null,
  current_version_id bigint null,
  last_task_id bigint null,
  status varchar(32) not null,
  created_by bigint not null,
  created_at datetime not null,
  updated_at datetime not null,
  deleted_at datetime null,
  index idx_review_project_tenant (tenant_id, created_at),
  index idx_review_project_status (status, updated_at)
);

create table review_script_version (
  id bigint primary key auto_increment,
  tenant_id bigint not null,
  project_id bigint not null,
  version_no int not null,
  source_type varchar(32) not null,
  file_name varchar(255) null,
  content longtext not null,
  created_by bigint not null,
  created_at datetime not null,
  updated_at datetime not null,
  deleted_at datetime null,
  unique key uk_review_version (tenant_id, project_id, version_no),
  index idx_review_version_project (tenant_id, project_id, created_at)
);

create table review_task (
  id bigint primary key auto_increment,
  tenant_id bigint not null,
  project_id bigint not null,
  script_version_id bigint not null,
  round_no int not null,
  review_mode varchar(32) not null,
  selected_dimensions_json longtext not null,
  review_scope_type varchar(32) not null,
  review_scope_json longtext null,
  global_index_json longtext null,
  result_json longtext null,
  status varchar(32) not null,
  current_stage varchar(64) null,
  overall_progress int not null default 0,
  current_action varchar(500) null,
  error_code varchar(64) null,
  error_message varchar(1000) null,
  idempotency_key varchar(200) not null,
  created_by bigint not null,
  created_at datetime not null,
  updated_at datetime not null,
  completed_at datetime null,
  canceled_at datetime null,
  unique key uk_review_task_idempotency (tenant_id, idempotency_key),
  index idx_review_task_project_round (tenant_id, project_id, round_no),
  index idx_review_task_version (tenant_id, project_id, script_version_id),
  index idx_review_task_status (status, updated_at)
);

create table review_issue (
  id bigint primary key auto_increment,
  tenant_id bigint not null,
  project_id bigint not null,
  task_id bigint not null,
  script_version_id bigint not null,
  round_no int not null,
  issue_no varchar(32) not null,
  dimension varchar(64) not null,
  severity varchar(16) not null,
  title varchar(255) not null,
  position_json longtext null,
  excerpt longtext null,
  problem longtext null,
  evidence_json longtext null,
  suggestion longtext null,
  status varchar(32) not null,
  related_issue_no varchar(32) null,
  manually_resolved boolean not null default false,
  manually_resolved_at datetime null,
  manually_resolved_by bigint null,
  created_at datetime not null,
  updated_at datetime not null,
  index idx_review_issue_task_status (task_id, status),
  index idx_review_issue_round (tenant_id, project_id, round_no),
  unique key uk_review_issue_no (task_id, issue_no)
);

create table review_issue_hit (
  id bigint primary key auto_increment,
  tenant_id bigint not null,
  project_id bigint not null,
  task_id bigint not null,
  issue_id bigint not null,
  hit_no int not null,
  episode_no int null,
  scene_no varchar(64) null,
  shot_no int null,
  line_no int null,
  anchor_label varchar(255) null,
  excerpt longtext not null,
  entity_name varchar(255) null,
  selected boolean not null default true,
  replacement_text longtext null,
  created_at datetime not null,
  updated_at datetime not null,
  unique key uk_review_issue_hit (issue_id, hit_no),
  index idx_review_issue_hit_issue (issue_id, selected)
);

create table review_issue_event (
  id bigint primary key auto_increment,
  tenant_id bigint not null,
  project_id bigint not null,
  task_id bigint not null,
  issue_id bigint not null,
  event_type varchar(32) not null,
  previous_status varchar(32) null,
  new_status varchar(32) null,
  payload_json longtext null,
  created_by bigint not null,
  created_at datetime not null,
  index idx_review_issue_event_issue (issue_id, created_at)
);

create table review_batch_repair (
  id bigint primary key auto_increment,
  tenant_id bigint not null,
  project_id bigint not null,
  task_id bigint not null,
  issue_id bigint null,
  action_type varchar(32) not null,
  replacement_from longtext null,
  replacement_to longtext null,
  insertion_text longtext null,
  deletion_text longtext null,
  selected_hit_ids longtext null,
  status varchar(32) not null,
  created_by bigint not null,
  created_at datetime not null,
  updated_at datetime not null,
  applied_at datetime null,
  index idx_review_batch_task (task_id, created_at)
);

create table review_export_record (
  id bigint primary key auto_increment,
  tenant_id bigint not null,
  project_id bigint not null,
  version_id bigint not null,
  task_id bigint not null,
  export_type varchar(32) not null,
  export_status varchar(32) not null,
  file_name varchar(255) null,
  file_size bigint null,
  download_url varchar(1000) null,
  error_message varchar(1000) null,
  created_at datetime not null,
  updated_at datetime not null,
  index idx_review_export_version (tenant_id, project_id, version_id, created_at)
);
