create table ai_image_task (
  id bigint primary key auto_increment,
  tenant_id bigint not null,
  project_id bigint not null,
  task_type varchar(32) not null,
  target_type varchar(32) not null,
  target_id bigint not null,
  service_config_id bigint not null,
  provider_code varchar(64) not null,
  model varchar(128) not null,
  prompt text not null,
  negative_prompt text null,
  reference_images text null,
  aspect_ratio varchar(32) not null,
  image_count int not null,
  style varchar(64) null,
  quality varchar(32) null,
  seed varchar(64) null,
  status varchar(32) not null,
  error_message text null,
  started_at datetime null,
  completed_at datetime null,
  created_by bigint not null,
  created_at datetime not null,
  updated_at datetime not null,
  deleted_at datetime null,
  index idx_ai_image_task_project_created (tenant_id, project_id, created_at),
  index idx_ai_image_task_target (tenant_id, project_id, target_type, target_id),
  index idx_ai_image_task_status (tenant_id, project_id, status)
);

create table ai_image_result (
  id bigint primary key auto_increment,
  tenant_id bigint not null,
  project_id bigint not null,
  task_id bigint not null,
  target_type varchar(32) not null,
  target_id bigint not null,
  image_url varchar(1000) not null,
  storage_path varchar(1000) null,
  thumbnail_url varchar(1000) null,
  width int null,
  height int null,
  file_size bigint null,
  material_id bigint null,
  is_selected boolean not null,
  status varchar(32) not null,
  created_at datetime not null,
  updated_at datetime not null,
  index idx_ai_image_result_task (task_id),
  index idx_ai_image_result_target (tenant_id, project_id, target_type, target_id)
);

create table material (
  id bigint primary key auto_increment,
  tenant_id bigint not null,
  project_id bigint not null,
  material_type varchar(32) not null,
  source_type varchar(32) not null,
  source_task_id bigint null,
  name varchar(200) not null,
  url varchar(1000) not null,
  storage_path varchar(1000) null,
  mime_type varchar(100) null,
  file_size bigint null,
  width int null,
  height int null,
  created_by bigint not null,
  created_at datetime not null,
  index idx_material_project_created (tenant_id, project_id, created_at),
  index idx_material_source_task (source_task_id)
);
