package com.antshorttv.rbac;

import java.util.List;

final class RbacPermissions {

    static final List<RbacPermissionDefinition> ALL = List.of(
        new RbacPermissionDefinition("TENANT:VIEW", "查看团队", PermissionType.PAGE, "TENANT", "VIEW"),
        new RbacPermissionDefinition("TENANT:EDIT", "修改团队", PermissionType.BUTTON, "TENANT", "EDIT"),
        new RbacPermissionDefinition("MEMBER:VIEW", "查看成员", PermissionType.PAGE, "MEMBER", "VIEW"),
        new RbacPermissionDefinition("MEMBER:INVITE", "邀请成员", PermissionType.BUTTON, "MEMBER", "INVITE"),
        new RbacPermissionDefinition("MEMBER:REMOVE", "移除成员", PermissionType.BUTTON, "MEMBER", "REMOVE"),
        new RbacPermissionDefinition("ROLE:VIEW", "查看角色", PermissionType.PAGE, "ROLE", "VIEW"),
        new RbacPermissionDefinition("ROLE:CREATE", "创建角色", PermissionType.BUTTON, "ROLE", "CREATE"),
        new RbacPermissionDefinition("ROLE:EDIT", "编辑角色", PermissionType.BUTTON, "ROLE", "EDIT"),
        new RbacPermissionDefinition("ROLE:DELETE", "删除角色", PermissionType.BUTTON, "ROLE", "DELETE"),
        new RbacPermissionDefinition("ORGANIZATION:VIEW", "查看组织", PermissionType.PAGE, "ORGANIZATION", "VIEW"),
        new RbacPermissionDefinition("ORGANIZATION:CREATE", "创建组织", PermissionType.BUTTON, "ORGANIZATION", "CREATE"),
        new RbacPermissionDefinition("ORGANIZATION:EDIT", "编辑组织", PermissionType.BUTTON, "ORGANIZATION", "EDIT"),
        new RbacPermissionDefinition("ORGANIZATION:DELETE", "删除组织", PermissionType.BUTTON, "ORGANIZATION", "DELETE"),
        new RbacPermissionDefinition("PROJECT:VIEW", "查看项目", PermissionType.PAGE, "PROJECT", "VIEW"),
        new RbacPermissionDefinition("PROJECT:CREATE", "创建项目", PermissionType.BUTTON, "PROJECT", "CREATE"),
        new RbacPermissionDefinition("PROJECT:EDIT", "编辑项目", PermissionType.BUTTON, "PROJECT", "EDIT"),
        new RbacPermissionDefinition("PROJECT:DELETE", "删除项目", PermissionType.BUTTON, "PROJECT", "DELETE"),
        new RbacPermissionDefinition("PROJECT_MEMBER:VIEW", "查看项目成员", PermissionType.PAGE, "PROJECT_MEMBER", "VIEW"),
        new RbacPermissionDefinition("PROJECT_MEMBER:ADD", "添加项目成员", PermissionType.BUTTON, "PROJECT_MEMBER", "ADD"),
        new RbacPermissionDefinition("PROJECT_MEMBER:UPDATE", "修改项目成员", PermissionType.BUTTON, "PROJECT_MEMBER", "UPDATE"),
        new RbacPermissionDefinition("PROJECT_MEMBER:REMOVE", "移除项目成员", PermissionType.BUTTON, "PROJECT_MEMBER", "REMOVE"),
        new RbacPermissionDefinition("PROJECT_ROLE:VIEW", "查看项目角色", PermissionType.PAGE, "PROJECT_ROLE", "VIEW"),
        new RbacPermissionDefinition("PROJECT_ROLE:CREATE", "创建项目角色", PermissionType.BUTTON, "PROJECT_ROLE", "CREATE"),
        new RbacPermissionDefinition("PROJECT_ROLE:UPDATE", "编辑项目角色", PermissionType.BUTTON, "PROJECT_ROLE", "UPDATE"),
        new RbacPermissionDefinition("PROJECT_ROLE:DELETE", "删除项目角色", PermissionType.BUTTON, "PROJECT_ROLE", "DELETE"),
        new RbacPermissionDefinition("PROJECT_ROLE:PERMISSION", "配置项目角色权限", PermissionType.BUTTON, "PROJECT_ROLE", "PERMISSION"),
        new RbacPermissionDefinition("SCRIPT:VIEW", "查看剧本", PermissionType.PAGE, "SCRIPT", "VIEW"),
        new RbacPermissionDefinition("SCRIPT:CREATE", "创建剧本", PermissionType.BUTTON, "SCRIPT", "CREATE"),
        new RbacPermissionDefinition("SCRIPT:EDIT", "编辑剧本", PermissionType.BUTTON, "SCRIPT", "EDIT"),
        new RbacPermissionDefinition("SCRIPT:DELETE", "删除剧本", PermissionType.BUTTON, "SCRIPT", "DELETE"),
        new RbacPermissionDefinition("SCRIPT:AI_GENERATE", "AI生成剧本", PermissionType.BUTTON, "SCRIPT", "AI_GENERATE"),
        new RbacPermissionDefinition("SCRIPT:AI_REWRITE", "AI改写剧本", PermissionType.BUTTON, "SCRIPT", "AI_REWRITE"),
        new RbacPermissionDefinition("ELEMENT:VIEW", "查看元素库", PermissionType.PAGE, "ELEMENT", "VIEW"),
        new RbacPermissionDefinition("ELEMENT:AI_EXTRACT", "AI提取元素", PermissionType.BUTTON, "ELEMENT", "AI_EXTRACT"),
        new RbacPermissionDefinition("ELEMENT:EDIT", "编辑元素", PermissionType.BUTTON, "ELEMENT", "EDIT"),
        new RbacPermissionDefinition("STORYBOARD:VIEW", "查看分镜", PermissionType.PAGE, "STORYBOARD", "VIEW"),
        new RbacPermissionDefinition("STORYBOARD:AI_BREAKDOWN", "AI拆解分镜", PermissionType.BUTTON, "STORYBOARD", "AI_BREAKDOWN"),
        new RbacPermissionDefinition("STORYBOARD:EDIT", "编辑分镜", PermissionType.BUTTON, "STORYBOARD", "EDIT"),
        new RbacPermissionDefinition("PROMPT:AI_GENERATE", "AI生成提示词", PermissionType.BUTTON, "PROMPT", "AI_GENERATE"),
        new RbacPermissionDefinition("AI_SERVICE:VIEW", "查看AI服务", PermissionType.PAGE, "AI_SERVICE", "VIEW"),
        new RbacPermissionDefinition("AI_SERVICE:CREATE", "新增AI服务", PermissionType.BUTTON, "AI_SERVICE", "CREATE"),
        new RbacPermissionDefinition("AI_SERVICE:EDIT", "编辑AI服务", PermissionType.BUTTON, "AI_SERVICE", "EDIT"),
        new RbacPermissionDefinition("AI_SERVICE:DELETE", "删除AI服务", PermissionType.BUTTON, "AI_SERVICE", "DELETE"),
        new RbacPermissionDefinition("AI_SERVICE:TEST", "测试AI服务", PermissionType.BUTTON, "AI_SERVICE", "TEST"),
        new RbacPermissionDefinition("AI_SERVICE:USE", "使用AI服务", PermissionType.BUTTON, "AI_SERVICE", "USE"),
        new RbacPermissionDefinition("AI_VIDEO_TASK:VIEW", "查看视频生成任务", PermissionType.PAGE, "AI_VIDEO_TASK", "VIEW"),
        new RbacPermissionDefinition("AI_VIDEO_TASK:CREATE", "创建视频生成任务", PermissionType.BUTTON, "AI_VIDEO_TASK", "CREATE"),
        new RbacPermissionDefinition("AI_VIDEO_TASK:CANCEL", "取消视频生成任务", PermissionType.BUTTON, "AI_VIDEO_TASK", "CANCEL"),
        new RbacPermissionDefinition("AI_VIDEO_TASK:DELETE", "删除视频生成记录", PermissionType.BUTTON, "AI_VIDEO_TASK", "DELETE"),
        new RbacPermissionDefinition("AI_VIDEO_RESULT:SAVE", "保存生成视频", PermissionType.BUTTON, "AI_VIDEO_RESULT", "SAVE"),
        new RbacPermissionDefinition("AI_VIDEO_RESULT:BIND", "设置分镜视频", PermissionType.BUTTON, "AI_VIDEO_RESULT", "BIND"),
        new RbacPermissionDefinition("AI_VIDEO_RESULT:DOWNLOAD", "下载生成视频", PermissionType.BUTTON, "AI_VIDEO_RESULT", "DOWNLOAD"),
        new RbacPermissionDefinition("AI_VOICE_TASK:VIEW", "查看语音合成任务", PermissionType.PAGE, "AI_VOICE_TASK", "VIEW"),
        new RbacPermissionDefinition("AI_VOICE_TASK:CREATE", "创建语音合成任务", PermissionType.BUTTON, "AI_VOICE_TASK", "CREATE"),
        new RbacPermissionDefinition("AI_VOICE_TASK:CANCEL", "取消语音合成任务", PermissionType.BUTTON, "AI_VOICE_TASK", "CANCEL"),
        new RbacPermissionDefinition("AI_VOICE_TASK:DELETE", "删除语音合成记录", PermissionType.BUTTON, "AI_VOICE_TASK", "DELETE"),
        new RbacPermissionDefinition("AI_VOICE_RESULT:SAVE", "保存语音结果", PermissionType.BUTTON, "AI_VOICE_RESULT", "SAVE"),
        new RbacPermissionDefinition("AI_VOICE_RESULT:BIND", "设置分镜音频", PermissionType.BUTTON, "AI_VOICE_RESULT", "BIND"),
        new RbacPermissionDefinition("AI_VOICE_RESULT:DOWNLOAD", "下载语音结果", PermissionType.BUTTON, "AI_VOICE_RESULT", "DOWNLOAD"),
        new RbacPermissionDefinition("SUBTITLE:VIEW", "查看字幕", PermissionType.PAGE, "SUBTITLE", "VIEW"),
        new RbacPermissionDefinition("SUBTITLE:EDIT", "编辑字幕", PermissionType.BUTTON, "SUBTITLE", "EDIT"),
        new RbacPermissionDefinition("SUBTITLE:DELETE", "删除字幕记录", PermissionType.BUTTON, "SUBTITLE", "DELETE"),
        new RbacPermissionDefinition("SHOT_COMPOSE:VIEW", "查看单镜头合成任务", PermissionType.PAGE, "SHOT_COMPOSE", "VIEW"),
        new RbacPermissionDefinition("SHOT_COMPOSE:CREATE", "创建单镜头合成任务", PermissionType.BUTTON, "SHOT_COMPOSE", "CREATE"),
        new RbacPermissionDefinition("SHOT_COMPOSE:SAVE", "保存单镜头结果", PermissionType.BUTTON, "SHOT_COMPOSE", "SAVE"),
        new RbacPermissionDefinition("SHOT_COMPOSE:DOWNLOAD", "下载单镜头结果", PermissionType.BUTTON, "SHOT_COMPOSE", "DOWNLOAD"),
        new RbacPermissionDefinition("SHOT_COMPOSE:DELETE", "删除单镜头合成记录", PermissionType.BUTTON, "SHOT_COMPOSE", "DELETE"),
        new RbacPermissionDefinition("SHOT_COMPOSE:BIND", "设置当前单镜头视频", PermissionType.BUTTON, "SHOT_COMPOSE", "BIND"),
        new RbacPermissionDefinition("AI_IMAGE_TASK:VIEW", "查看图片生成任务", PermissionType.PAGE, "AI_IMAGE_TASK", "VIEW"),
        new RbacPermissionDefinition("AI_IMAGE_TASK:CREATE", "创建图片生成任务", PermissionType.BUTTON, "AI_IMAGE_TASK", "CREATE"),
        new RbacPermissionDefinition("AI_IMAGE_TASK:CANCEL", "取消图片生成任务", PermissionType.BUTTON, "AI_IMAGE_TASK", "CANCEL"),
        new RbacPermissionDefinition("AI_IMAGE_TASK:DELETE", "删除图片生成记录", PermissionType.BUTTON, "AI_IMAGE_TASK", "DELETE"),
        new RbacPermissionDefinition("AI_IMAGE_RESULT:SAVE", "保存生成图片", PermissionType.BUTTON, "AI_IMAGE_RESULT", "SAVE"),
        new RbacPermissionDefinition("AI_IMAGE_RESULT:BIND", "设置业务主图", PermissionType.BUTTON, "AI_IMAGE_RESULT", "BIND")
    );

    private RbacPermissions() {
    }
}
