package com.antshorttv.script;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import com.antshorttv.workflowagent.run.WorkflowAgentRunRepository;
import com.antshorttv.workflowagent.tool.ToolExecutionContext;
import com.antshorttv.workflowagent.tool.WorkflowToolRunState;
import java.util.List;
import java.util.Set;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;

class EpisodeFanoutCommitEvidenceTest {
    private JdbcTemplate jdbc;
    private TransactionTemplate transactions;
    private WorkflowAgentRunRepository runs;
    private JdbcEpisodeFanoutStore store;

    @BeforeEach
    void setUp() {
        var source = new JdbcDataSource();
        source.setURL("jdbc:h2:mem:fanout_" + java.util.UUID.randomUUID() + ";MODE=MySQL;DB_CLOSE_DELAY=-1");
        jdbc = new JdbcTemplate(source);
        transactions = new TransactionTemplate(new DataSourceTransactionManager(source));
        runs = mock(WorkflowAgentRunRepository.class);
        store = new JdbcEpisodeFanoutStore(jdbc, runs);
        jdbc.execute("create table script_analysis_stage(id bigint primary key, attempt_no int)");
        jdbc.execute("create table script_analysis_fanout_snapshot(id bigint generated by default as identity primary key, tenant_id bigint, project_id bigint, script_id bigint, task_id bigint, stage_id bigint, stage_code varchar, agent_code varchar, model_id bigint, attempt_no int, status varchar)");
        jdbc.execute("create table script_analysis_fanout_unit(snapshot_id bigint, episode_id bigint, episode_key varchar, content_fingerprint varchar, status varchar, attempt_no int, child_run_id bigint, updated_at timestamp)");
        jdbc.execute("create table ai_workflow_agent_run(id bigint primary key, tenant_id bigint, project_id bigint, script_id bigint, task_id bigint, analysis_stage_id bigint, episode_id bigint, agent_code varchar, model_id bigint, run_type varchar)");
        jdbc.execute("create table script_episode(id bigint primary key, tenant_id bigint, project_id bigint, script_id bigint, stable_key varchar, content_fingerprint varchar, status varchar, retired_at timestamp)");
        jdbc.execute("create table script_episode_summary(tenant_id bigint, project_id bigint, script_id bigint, episode_id bigint, source varchar, generated_by_run_id bigint)");
        jdbc.execute("create table script_episode_asset_analysis(tenant_id bigint, project_id bigint, script_id bigint, episode_id bigint, content_fingerprint varchar, generated_by_run_id bigint)");
        jdbc.update("insert into script_analysis_stage values(5, 2)");
        jdbc.update("insert into script_analysis_fanout_snapshot values(50, 7, 8, 9, 4, 5, 'EPISODE_SUMMARY', 'short-drama-episode-summary', 99, 2, 'RUNNING')");
        jdbc.update("insert into script_analysis_fanout_unit values(50, 1, 'e1', 'fp', 'RUNNING', 2, null, now())");
        jdbc.update("insert into ai_workflow_agent_run values(901, 7, 8, 9, 4, 5, 1, 'short-drama-episode-summary', 99, 'FORMAL')");
        jdbc.update("insert into script_episode values(1, 7, 8, 9, 'e1', 'fp', 'ACTIVE', null)");
    }

    @ParameterizedTest
    @ValueSource(booleans = {false, true})
    void committedOutputSurvivesCrashBeforeUnitSuccess(boolean assets) {
        if (assets) {
            jdbc.update("update script_analysis_fanout_snapshot set stage_code='CHARACTER_SCENE_RECOGNITION', agent_code='short-drama-asset-recognition'");
            jdbc.update("update ai_workflow_agent_run set agent_code='short-drama-asset-recognition'");
        }
        transactions.executeWithoutResult(status -> {
            if (assets) jdbc.update("insert into script_episode_asset_analysis values(7,8,9,1,'fp',901)");
            else jdbc.update("insert into script_episode_summary values(7,8,9,1,'AI',901)");
            EpisodeFanoutCommitEvidence.record(jdbc, context(2), "fp");
        });
        when(runs.modelCalls(901L, 7L)).thenReturn(List.of());

        var recovered = store.recoverCommitted(50L, 1L);

        assertThat(recovered).isPresent();
        assertThat(recovered.orElseThrow().runId()).isEqualTo(901L);
        verify(runs).reconcileCommitted(901L, "{\"saved\":true,\"reconciled\":true}");
    }

    @ParameterizedTest
    @ValueSource(strings = {"tenant_id", "project_id", "script_id", "task_id", "analysis_stage_id", "episode_id", "model_id", "agent_code", "run_type", "source", "current_source", "output_run", "missing_receipt"})
    void refusesUnrelatedOrStaleFormalOutput(String mismatch) {
        jdbc.update("insert into script_episode_summary values(7,8,9,1,'AI',901)");
        EpisodeFanoutCommitEvidence.record(jdbc, context(2), "fp");
        switch (mismatch) {
            case "agent_code", "run_type" -> jdbc.update("update ai_workflow_agent_run set " + mismatch + " = 'other'");
            case "source" -> jdbc.update("update script_episode_summary set source='USER'");
            case "current_source" -> jdbc.update("update script_episode set content_fingerprint='changed'");
            case "output_run" -> jdbc.update("update script_episode_summary set generated_by_run_id=902");
            case "missing_receipt" -> jdbc.update("update script_analysis_fanout_unit set child_run_id=null");
            default -> jdbc.update("update ai_workflow_agent_run set " + mismatch + " = 999");
        }

        assertThat(store.recoverCommitted(50L, 1L)).isEmpty();
        org.mockito.Mockito.verifyNoInteractions(runs);
    }

    @Test
    void retryReusesPreparedPendingSnapshotAndKeepsCommittedUnits() {
        for (String column : List.of("agent_revision bigint default 3", "episode_set_hash varchar default 'hash'",
            "total_units int default 2", "completed_units int default 1", "failed_units int default 0",
            "created_at timestamp", "updated_at timestamp")) {
            jdbc.execute("alter table script_analysis_fanout_snapshot add column " + column);
        }
        for (String column : List.of("error_code varchar", "error_message varchar", "finished_at timestamp",
            "created_at timestamp")) {
            jdbc.execute("alter table script_analysis_fanout_unit add column " + column);
        }
        jdbc.update("update script_analysis_fanout_snapshot set status='PENDING'");
        jdbc.update("update script_analysis_stage set attempt_no=3");
        jdbc.update("update script_analysis_fanout_unit set status='SUCCEEDED', child_run_id=901");
        jdbc.update("insert into script_analysis_fanout_unit(snapshot_id, episode_id, episode_key, content_fingerprint, status, attempt_no) values(50,2,'e2','fp2','PENDING',0)");
        var task = new ScriptAnalysisTaskEntity();
        task.setId(4L); task.setTenantId(7L); task.setProjectId(8L); task.setScriptId(9L);
        var stage = new ScriptAnalysisStageEntity();
        stage.setId(5L); stage.setStageCode("EPISODE_SUMMARY"); stage.setAttemptNo(3);
        var plan = mock(com.antshorttv.workflowagent.run.WorkflowAgentExecutionPlan.class);
        var agent = mock(com.antshorttv.workflowagent.agent.WorkflowAgentRecord.class);
        when(plan.agent()).thenReturn(agent);
        when(agent.revision()).thenReturn(3L);
        var episodes = List.of(new EpisodeFanoutCoordinator.EpisodeUnit(1L,"e1","fp","ACTIVE"),
            new EpisodeFanoutCoordinator.EpisodeUnit(2L,"e2","fp2","ACTIVE"));

        long snapshotId = store.openSnapshot(task, stage, "short-drama-episode-summary", plan,
            99L, episodes, "hash", false);

        assertThat(snapshotId).isEqualTo(50L);
        assertThat(jdbc.queryForObject("select count(*) from script_analysis_fanout_unit", Integer.class)).isEqualTo(2);
        assertThat(jdbc.queryForObject("select status from script_analysis_fanout_unit where episode_id=1", String.class))
            .isEqualTo("SUCCEEDED");
    }

    @Test
    void lostUnitClaimRollsBackTheFormalOutputTransaction() {
        assertThatThrownBy(() -> transactions.executeWithoutResult(status -> {
            jdbc.update("insert into script_episode_summary values(7,8,9,1,'AI',901)");
            EpisodeFanoutCommitEvidence.record(jdbc, context(1), "fp");
        })).hasMessageContaining("正式保存已回滚");

        assertThat(jdbc.queryForObject("select count(*) from script_episode_summary", Integer.class)).isZero();
        assertThat(jdbc.queryForObject("select child_run_id from script_analysis_fanout_unit", Long.class)).isNull();
    }

    private ToolExecutionContext context(int attempt) {
        var state = new WorkflowToolRunState();
        state.put("fanoutSnapshotId", 50L);
        state.put("fanoutUnitAttemptNo", attempt);
        return new ToolExecutionContext(7L, 10L, 8L, 1L, 9L, 4L, 5L, 901L, Set.of(), null, state);
    }
}
